<?php
return [
	'host'=>[
		'host'=>'127.0.0.1',
		'port'=>3306,
		'user'=>'root',
		'passwd'=>'lovewes520',
		'dbname'=>'fym_host',
		'prifix'=>'fym_'
	],
	'source'=>[
		'host'=>'127.0.0.1',
		'port'=>3306,
		'user'=>'root',
		'passwd'=>'lovewes520',
		'dbname'=>'fym_source',
		'prifix'=>'fym_'
	],
	'user'=>[
		'host'=>'127.0.0.1',
		'port'=>3306,
		'user'=>'root',
		'passwd'=>'lovewes520',
		'dbname'=>'fym_user',
		'prifix'=>'fym_'
	],
	'temp'=>[
		'host'=>'127.0.0.1',
		'port'=>3306,
		'user'=>'root',
		'passwd'=>'lovewes520',
		'dbname'=>'fym_temp',
		'prifix'=>'fym_'
	],
	'redis'=>[
		'host'=>'127.0.0.1',
		'port'=>6379,
		'passwd'=>'',
		'dbname'=>'3',
		'prifix'=>'fym_'
	],
	'extra'=>[
		'hostSeparator'=>'////',
		'seoSeparator'=>'///',
		'tempMax'=>600000,
		'tableMax'=>2000000,
	]
];
